### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by troyxmccall** [alexmt/atom-translator#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [translator](https://github.com/alexmt/atom-translator) package, v0.2.0
### Stack Trace

Uncaught TypeError: Cannot read property 'prototype' of undefined

```
At /Users/tdmccall/.atom/packages/translator/lib/language-selector-view.coffee:4

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/tdmccall/.atom/packages/translator/lib/language-selector-view.coffee:4:199)
  at /Users/tdmccall/.atom/packages/translator/lib/language-selector-view.coffee:6:3
  at Object.<anonymous> (/Users/tdmccall/.atom/packages/translator/lib/language-selector-view.coffee:81:5)
  at Object.<anonymous> (/Users/tdmccall/.atom/packages/translator/lib/language-selector-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/tdmccall/.atom/packages/translator/lib/translator-view.coffee:2:24)
  at Object.<anonymous> (/Users/tdmccall/.atom/packages/translator/lib/translator-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/tdmccall/.atom/packages/translator/lib/translator.coffee:2:18)
  at Object.<anonymous> (/Users/tdmccall/.atom/packages/translator/lib/translator.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:257:12)
  at PackageDetailView.module.exports.PackageDetailView.activate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:163:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:201:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:235:24
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at PackageManager.module.exports.Emitter.emitSlow (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:154:47)
  at PackageManager.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:107:30)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:546:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:369:26
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
     -9:07.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -9:06.9.0 core:save (atom-text-editor.editor.is-focused)
  2x -9:03.0 core:backspace (atom-text-editor.editor.is-focused)
     -9:02.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -9:01.2.0 core:save (atom-text-editor.editor.is-focused)
     -8:58 core:backspace (atom-text-editor.editor.is-focused)
     -8:57.6.0 core:move-right (atom-text-editor.editor.is-focused)
  6x -8:57.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -8:46.4.0 core:save (atom-text-editor.editor.is-focused)
     -8:35.4.0 core:copy (atom-text-editor.editor.is-focused)
     -2:16.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:13.2.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:55.5.0 settings-view:open (atom-text-editor.editor.is-focused)
  2x -0:51.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:23.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:21.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "flatland-dark-ui",
      "atom-monokai"
    ],
    "disabledPackages": [
      "wrap-guide"
    ],
    "projectHome": "Default: ~/projects/"
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.7
atom-monokai, v0.8.0
auto-update-packages, v1.0.0
autocomplete-php, v0.3.6
compass, v0.9.1
emmet, v2.3.12
flatland-dark-ui, v0.2.4
language-applescript, v0.2.0
linter-php, v0.0.15
linter-scss-lint, v1.0.5
minimap, v4.10.2
php-debug, v0.1.2
tabs-to-spaces, v0.11.0
trailing-spaces, v0.3.2
wordpress-api, v1.2.1

# Dev
No dev packages
```

**Comment by alexmt** [comment]
Thank you for reporting this issue!

Fixed: https://github.com/alexmt/atom-translator/commit/ad6ee1542ee402f28d1cff2044b26f1ca602d4f4
