### ISSUE TITLE
Uncaught TypeError: Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by jacklam718** [alexmt/atom-translator#9]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.11.6
**Thrown From**: [translator](https://github.com/alexmt/atom-translator) package 0.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'join' of undefined

```
At /Users/jack/.atom/packages/translator/lib/translation-service.coffee:70

TypeError: Cannot read property 'join' of undefined
    at TranslationService.module.exports.TranslationService.translateTextLines (/packages/translator/lib/translation-service.coffee:70:18)
    at Object.refreshViewTranslation (/packages/translator/lib/translator.coffee:44:35)
    at /packages/translator/lib/translator.coffee:33:52)
    at HTMLDivElement.dispatch (/packages/json-schema/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/json-schema/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
    at Object.trigger (/packages/json-schema/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4350:12)
    at /packages/json-schema/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4901:17)
    at Function.each (/packages/json-schema/node_modules/space-pen/node_modules/jquery/dist/jquery.js:374:23)
    at TranslatorView.each (/packages/json-schema/node_modules/space-pen/node_modules/jquery/dist/jquery.js:139:17)
    at /packages/json-schema/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4900:15)
    at /packages/json-schema/node_modules/space-pen/lib/space-pen.js:606:19)
    at TranslatorView.module.exports.TranslatorView.requestTranslation (/packages/translator/lib/translator-view.coffee:66:6)
    at TranslatorView.requestTranslation (/packages/translator/lib/translator-view.coffee:1:1)
    at TranslatorView.module.exports.TranslatorView.switchLangs (/packages/translator/lib/translator-view.coffee:57:6)
    at /packages/json-schema/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.dispatch (/packages/json-schema/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/packages/json-schema/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -2:40.7.0 core:backspace (input.hidden-input)
     -2:26.7.0 editor:select-to-first-character-of-line (input.hidden-input)
     -2:23.9.0 core:confirm (input.hidden-input)
     -2:07.8.0 core:cancel (div.package-detail.panels-item)
     -1:58.8.0 editor:select-to-first-character-of-line (input.hidden-input)
     -1:55.4.0 core:confirm (input.hidden-input)
  6x -1:53.6.0 core:backspace (input.hidden-input)
     -1:47.5.0 core:confirm (input.hidden-input)
     -0:41.3.0 datatip:toggle (input.hidden-input)
     -0:40.4.0 intentions:highlight (input.hidden-input)
     -0:39.6.0 datatip:toggle (input.hidden-input)
     -0:37.1.0 application:new-file (input.hidden-input)
     -0:33.9.0 intentions:highlight (input.hidden-input)
     -0:33.5.0 datatip:toggle (input.hidden-input)
     -0:32.1.0 translator:translate (input.hidden-input)
     -0:30.3.0 datatip:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-ternjs 0.18.3 
autocomplete-json 5.5.0 
busy-signal 1.4.3 
color-picker 2.2.5 
highlight-selected 0.13.1 
intentions 1.1.5 
json-schema 0.1.15 
linter 2.0.0 
linter-eslint 8.2.1 
linter-travis-lint 1.0.0 
linter-ui-default 1.6.7 
markdown-preview-plus 2.4.10 
minimap 4.29.6 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
nuclide 0.245.0 
nuclide-format-js 0.0.41 
pretty-json 1.6.4 
react-native-snippets 0.3.0 
translator 0.3.0 
```

**Comment by CRaFT4ik** [comment]
+1, it's not work for me.

**Comment by CerebralMischief** [comment]
I am also seeing this error.  The plugin doesn't work.  I'm using Arch Linux.
